networks:
  test-network:
    external: true

services:
  data-center:
    image: golang:1.24-bullseye
    container_name: test-data-center
    working_dir: /app
    environment:
      - DC_ID=28c2f2c2-590f-442d-bf80-7e6bbeb4c471
      - DC_ADDR=:8080
      - USE_GUEST=1
      - DB_ADDR=test-mariadb:3306
      - DB_USER=chris
      - DB_PW=123456
      - DB_NAME=game_dev
      - NATS_ADDR=test-nats:4222
    volumes:
      - /home/chris/git/wander/env_test/dist:/app
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    command: /app/dc
    networks:
      - test-network