networks:
  test-network:
    driver: bridge
    name: test-network

services:
  redis:
    image: redis:4.0.2-alpine
    container_name: test-redis
    ports:
      - "6379:6379"
    networks:
      - test-network

  mariadb:
    image: mariadb:10.11
    container_name: test-mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: chris
      MARIADB_PASSWORD: 123456
      MARIADB_DATABASE: game_dev
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "1"
    volumes:
      - /home/chris/data_store/game_dev:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - test-network

  nats:
    image: nats:2.10.26-alpine
    container_name: test-nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--http_port 8222"
    networks:
      - test-network

  make-file:
    image: golang:1.24-bullseye
    container_name: make-file
    working_dir: /app
    volumes:
      - /home/chris/git:/app
      - /home/chris/git/wander/env_test/dist:/dist
    command: sh -c "cd /app/wander/env_test && sh build.sh"
    stdin_open: true
    tty: true
    networks:
      - test-network
