services:
  redis:
    image: redis:4.0.2-alpine
    container_name: local-redis
    restart: always
    ports:
      - "6379:6379"

  mongo:
    image: mongo:4.4
    container_name: local-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /home/chris/data_store/game_dev/mongo:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "--eval", "db.runCommand({serverStatus:1}).ok"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  mongo-express:
    image: mongo-express:1.0
    container_name: local-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

  mariadb:
    image: mariadb:10.11
    container_name: local-mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: chris
      MARIADB_PASSWORD: 123456
      MARIADB_DATABASE: game_dev
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "1"
    volumes:
      - /home/chris/data_store/game_dev/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  nats:
    image: nats:2.10.26-alpine
    container_name: local-nats
    restart: always
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--http_port 8222"
