// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.1
// source: game_0001.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_BET    Action = 0
	Action_RAISE  Action = 1
	Action_FOLDER Action = 2
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "BET",
		1: "RAISE",
		2: "FOLDER",
	}
	Action_value = map[string]int32{
		"BET":    0,
		"RAISE":  1,
		"FOLDER": 2,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_game_0001_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_game_0001_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_game_0001_proto_rawDescGZIP(), []int{0}
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Wallet float64 `protobuf:"fixed64,2,opt,name=wallet,proto3" json:"wallet,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_0001_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_game_0001_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_game_0001_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetWallet() float64 {
	if x != nil {
		return x.Wallet
	}
	return 0
}

type OtherPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Action Action `protobuf:"varint,2,opt,name=action,proto3,enum=Action" json:"action,omitempty"`
}

func (x *OtherPlayer) Reset() {
	*x = OtherPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_0001_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OtherPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtherPlayer) ProtoMessage() {}

func (x *OtherPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_game_0001_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtherPlayer.ProtoReflect.Descriptor instead.
func (*OtherPlayer) Descriptor() ([]byte, []int) {
	return file_game_0001_proto_rawDescGZIP(), []int{1}
}

func (x *OtherPlayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OtherPlayer) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_BET
}

type Limite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min uint64 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max uint64 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *Limite) Reset() {
	*x = Limite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_0001_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Limite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limite) ProtoMessage() {}

func (x *Limite) ProtoReflect() protoreflect.Message {
	mi := &file_game_0001_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limite.ProtoReflect.Descriptor instead.
func (*Limite) Descriptor() ([]byte, []int) {
	return file_game_0001_proto_rawDescGZIP(), []int{2}
}

func (x *Limite) GetMin() uint64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Limite) GetMax() uint64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 唯一碼
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 入桌狀態{true:當前,false:否}
	Actived bool `protobuf:"varint,2,opt,name=actived,proto3" json:"actived,omitempty"`
	// 顯示名稱
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 下注上下限
	BetLimite *Limite `protobuf:"bytes,4,opt,name=bet_limite,json=betLimite,proto3" json:"bet_limite,omitempty"`
	// 總彩池上限/總封頂/底池上限
	PoolLimite *Limite `protobuf:"bytes,5,opt,name=pool_limite,json=poolLimite,proto3" json:"pool_limite,omitempty"`
	// 依坐位順序
	OtherPlayer []*OtherPlayer `protobuf:"bytes,6,rep,name=other_player,json=otherPlayer,proto3" json:"other_player,omitempty"`
}

func (x *Room) Reset() {
	*x = Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_0001_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_game_0001_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_game_0001_proto_rawDescGZIP(), []int{3}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetActived() bool {
	if x != nil {
		return x.Actived
	}
	return false
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetBetLimite() *Limite {
	if x != nil {
		return x.BetLimite
	}
	return nil
}

func (x *Room) GetPoolLimite() *Limite {
	if x != nil {
		return x.PoolLimite
	}
	return nil
}

func (x *Room) GetOtherPlayer() []*OtherPlayer {
	if x != nil {
		return x.OtherPlayer
	}
	return nil
}

type Init struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *Player          `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Rooms  map[string]*Room `protobuf:"bytes,2,rep,name=rooms,proto3" json:"rooms,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// 當前在那桌
	RoomId string `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *Init) Reset() {
	*x = Init{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_0001_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Init) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Init) ProtoMessage() {}

func (x *Init) ProtoReflect() protoreflect.Message {
	mi := &file_game_0001_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Init.ProtoReflect.Descriptor instead.
func (*Init) Descriptor() ([]byte, []int) {
	return file_game_0001_proto_rawDescGZIP(), []int{4}
}

func (x *Init) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *Init) GetRooms() map[string]*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *Init) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

var File_game_0001_proto protoreflect.FileDescriptor

var file_game_0001_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x30, 0x30, 0x30, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x34, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x06, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x22, 0x42, 0x0a, 0x0b, 0x4f, 0x74, 0x68, 0x65, 0x72,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2c, 0x0a, 0x06, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0xc7, 0x01, 0x0a, 0x04, 0x52, 0x6f,
	0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x0a, 0x62, 0x65, 0x74, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x52, 0x09, 0x62,
	0x65, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x0b, 0x70, 0x6f, 0x6f, 0x6c,
	0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x52, 0x0a, 0x70, 0x6f, 0x6f, 0x6c, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x65, 0x12, 0x2f, 0x0a, 0x0c, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4f, 0x74, 0x68, 0x65, 0x72,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0b, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x22, 0xa9, 0x01, 0x0a, 0x04, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x1f, 0x0a, 0x06,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x26, 0x0a,
	0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x49,
	0x6e, 0x69, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05,
	0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x1a, 0x3f,
	0x0a, 0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1b,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a,
	0x28, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x45, 0x54,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x41, 0x49, 0x53, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x46, 0x4f, 0x4c, 0x44, 0x45, 0x52, 0x10, 0x02, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_0001_proto_rawDescOnce sync.Once
	file_game_0001_proto_rawDescData = file_game_0001_proto_rawDesc
)

func file_game_0001_proto_rawDescGZIP() []byte {
	file_game_0001_proto_rawDescOnce.Do(func() {
		file_game_0001_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_0001_proto_rawDescData)
	})
	return file_game_0001_proto_rawDescData
}

var file_game_0001_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_0001_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_game_0001_proto_goTypes = []interface{}{
	(Action)(0),         // 0: Action
	(*Player)(nil),      // 1: Player
	(*OtherPlayer)(nil), // 2: OtherPlayer
	(*Limite)(nil),      // 3: Limite
	(*Room)(nil),        // 4: Room
	(*Init)(nil),        // 5: Init
	nil,                 // 6: Init.RoomsEntry
}
var file_game_0001_proto_depIdxs = []int32{
	0, // 0: OtherPlayer.action:type_name -> Action
	3, // 1: Room.bet_limite:type_name -> Limite
	3, // 2: Room.pool_limite:type_name -> Limite
	2, // 3: Room.other_player:type_name -> OtherPlayer
	1, // 4: Init.player:type_name -> Player
	6, // 5: Init.rooms:type_name -> Init.RoomsEntry
	4, // 6: Init.RoomsEntry.value:type_name -> Room
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_game_0001_proto_init() }
func file_game_0001_proto_init() {
	if File_game_0001_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_0001_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_0001_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OtherPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_0001_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Limite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_0001_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_0001_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Init); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_0001_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_0001_proto_goTypes,
		DependencyIndexes: file_game_0001_proto_depIdxs,
		EnumInfos:         file_game_0001_proto_enumTypes,
		MessageInfos:      file_game_0001_proto_msgTypes,
	}.Build()
	File_game_0001_proto = out.File
	file_game_0001_proto_rawDesc = nil
	file_game_0001_proto_goTypes = nil
	file_game_0001_proto_depIdxs = nil
}
